"""Add CONSISTENCY_SWEEP to the ai_feature enum.

A one-value migration, and a dialect-specific one.

On PostgreSQL ``ai_feature`` is a native ENUM type, so a new value needs
``ALTER TYPE ... ADD VALUE``. On SQLite -- which is what the test suite runs against --
SQLAlchemy renders the same column as a plain VARCHAR with no CHECK constraint, so there
is nothing to alter and this migration is correctly a no-op there.

That asymmetry is why it is written out rather than autogenerated: Alembic's autogenerate
does not detect enum value changes on either dialect, so a value added to the Python enum
and forgotten here would work in every test and fail on the first real deployment.

The downgrade does not remove the value. PostgreSQL has no ``ALTER TYPE ... DROP VALUE``,
and the alternatives -- rebuild the type, rewrite the column -- would risk data for no
benefit, since an unused enum value is inert. The tables this touches are dropped whole
by 0007's downgrade anyway.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_VALUE = "CONSISTENCY_SWEEP"


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    # ADD VALUE cannot run inside a transaction block on PostgreSQL before 12, and
    # Alembic wraps migrations in one. COMMIT first, then add.
    op.execute("COMMIT")
    op.execute(f"ALTER TYPE ai_feature ADD VALUE IF NOT EXISTS '{NEW_VALUE}'")


def downgrade() -> None:
    # Deliberately empty. See the module docstring: PostgreSQL cannot drop an enum
    # value, and an unused one is inert.
    pass
