"""retain event triage and incident response decisions

Revision ID: 0020
Revises: 0019
Create Date: 2026-09-27 17:03:16.345008
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0020'
down_revision: str | None = '0019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_ref', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('reported_on', sa.Date(), nullable=False),
    sa.Column('reporter', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('classification_note', sa.Text(), nullable=False),
    sa.Column('notification_decision', sa.Text(), nullable=False),
    sa.Column('lessons', sa.Text(), nullable=False),
    sa.Column('closure_note', sa.Text(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('UNASSESSED','LOW','MEDIUM','HIGH','CRITICAL')", name='ck_event_severity'),
    sa.CheckConstraint("status != 'CLOSED' OR (closed_on IS NOT NULL AND closed_on >= reported_on AND evidence_id IS NOT NULL AND length(trim(lessons))>0 AND length(trim(closure_note))>0)", name='ck_event_closure'),
    sa.CheckConstraint("status IN ('REPORTED','DISMISSED','INCIDENT','CONTAINED','RECOVERED','CLOSED')", name='ck_event_status'),
    sa.CheckConstraint("status NOT IN ('INCIDENT','CONTAINED','RECOVERED','CLOSED') OR (severity != 'UNASSESSED' AND length(trim(classification_note))>0)", name='ck_event_triage'),
    sa.CheckConstraint('length(trim(title))>0 AND length(trim(owner))>0 AND length(trim(description))>0', name='ck_event_required'),
    sa.CheckConstraint('reported_on >= occurred_on', name='ck_event_dates'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_ref')
    )
    op.create_table('incident_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('custody_note', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind != 'EVIDENCE' OR (attachment_id IS NOT NULL AND length(trim(custody_note))>0)", name='ck_incident_custody'),
    sa.CheckConstraint("kind IN ('TRIAGE','RESPONSE','COMMUNICATION','EVIDENCE','CONTAINED','RECOVERED','CLOSED','REOPENED')", name='ck_incident_entry_kind'),
    sa.CheckConstraint('length(trim(note))>0 AND length(trim(actor))>0', name='ck_incident_entry_required'),
    sa.ForeignKeyConstraint(['attachment_id'], ['evidence_attachments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_entries')
    op.drop_table('security_events')
    # ### end Alembic commands ###
