"""retain supplier reviews and owned follow-up actions

Revision ID: 0021
Revises: 0020
Create Date: 2026-09-27 17:08:46.618508
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0021'
down_revision: str | None = '0020'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_ref', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('information_access', sa.Text(), nullable=False),
    sa.Column('agreement_terms', sa.Text(), nullable=False),
    sa.Column('shared_responsibility', sa.Text(), nullable=False),
    sa.Column('exit_plan', sa.Text(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=True),
    sa.Column('agreement_attachment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_on', sa.Date(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("criticality IN ('UNASSESSED','LOW','MEDIUM','HIGH','CRITICAL')", name='ck_supplier_criticality'),
    sa.CheckConstraint("status != 'REVIEWED' OR (criticality != 'UNASSESSED' AND reviewed_on IS NOT NULL AND review_date > reviewed_on)", name='ck_supplier_review'),
    sa.CheckConstraint("status IN ('DRAFT','REVIEWED','EXITED')", name='ck_supplier_status'),
    sa.CheckConstraint('dependency_id IS NULL OR dependency_id != id', name='ck_supplier_self_dependency'),
    sa.CheckConstraint('length(trim(name))>0 AND length(trim(owner))>0 AND length(trim(service))>0', name='ck_supplier_required'),
    sa.ForeignKeyConstraint(['agreement_attachment_id'], ['evidence_attachments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dependency_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_ref')
    )
    op.create_table('supplier_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('action_owner', sa.String(length=160), nullable=True),
    sa.Column('action_due', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('completion_evidence_id', sa.Integer(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("result != 'ACTION_REQUIRED' OR (action_due IS NOT NULL AND length(trim(action_owner))>0 AND length(trim(action))>0)", name='ck_supplier_review_action'),
    sa.CheckConstraint("result IN ('ACCEPTABLE','ACTION_REQUIRED','EXIT')", name='ck_supplier_review_result'),
    sa.CheckConstraint('action_due IS NULL OR action_due >= reviewed_on', name='ck_supplier_action_date'),
    sa.ForeignKeyConstraint(['completion_evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_reviews')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
