"""retain competence evaluations and communication evidence

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-27 17:12:45.877105
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0022'
down_revision: str | None = '0021'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competence_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_ref', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('evaluation_method', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(trim(role))>0 AND length(trim(requirement))>0 AND length(trim(owner))>0', name='ck_competence_required'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_ref')
    )
    op.create_table('competence_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('demonstrated_outcome', sa.Text(), nullable=False),
    sa.Column('development_action', sa.Text(), nullable=True),
    sa.Column('action_due', sa.Date(), nullable=True),
    sa.Column('requirement_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("result != 'DEVELOPMENT_REQUIRED' OR (action_due IS NOT NULL AND length(trim(coalesce(development_action,'')))>0)", name='ck_competence_action'),
    sa.CheckConstraint("result IN ('DEVELOPMENT_REQUIRED','COMPETENT')", name='ck_competence_result'),
    sa.CheckConstraint('review_date > evaluated_on', name='ck_competence_dates'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['competence_requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communication_ref', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('planned_on', sa.Date(), nullable=False),
    sa.Column('document_revision_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delivered_on', sa.Date(), nullable=True),
    sa.Column('delivered_by', sa.String(length=64), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status != 'DELIVERED' OR (delivered_on IS NOT NULL AND evidence_id IS NOT NULL AND delivered_by IS NOT NULL)", name='ck_communication_delivery'),
    sa.CheckConstraint("status IN ('PLANNED','DELIVERED')", name='ck_communication_status'),
    sa.CheckConstraint('length(trim(audience))>0 AND length(trim(owner))>0 AND length(trim(method))>0', name='ck_communication_required'),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('communication_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_plans')
    op.drop_table('competence_evaluations')
    op.drop_table('competence_requirements')
    # ### end Alembic commands ###
