"""retain applicability authority and compliance evaluations

Revision ID: 0023
Revises: 0022
Create Date: 2026-09-27 17:24:13.186966
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0023'
down_revision: str | None = '0022'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obligation_ref', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_version', sa.String(length=160), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('applicability', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("applicability IN ('UNASSESSED','APPLICABLE','NOT_APPLICABLE')", name='ck_obligation_applicability'),
    sa.CheckConstraint("applicability='UNASSESSED' OR (approved_by IS NOT NULL AND approved_on IS NOT NULL AND length(trim(coalesce(rationale,'')))>0)", name='ck_obligation_approval'),
    sa.CheckConstraint("kind IN ('LEGAL','REGULATORY','CONTRACTUAL')", name='ck_obligation_kind'),
    sa.CheckConstraint('length(trim(source))>0 AND length(trim(source_version))>0 AND length(trim(owner))>0', name='ck_obligation_source'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_ref')
    )
    op.create_table('obligation_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('decided_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('APPLICABILITY','EVALUATION')", name='ck_obligation_decision_kind'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obligation_decisions')
    op.drop_table('obligations')
    # ### end Alembic commands ###
