"""review operational revisions and retain external proof

Revision ID: 0024
Revises: 0023
Create Date: 2026-09-28 00:42:40.702506
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0024'
down_revision: str | None = '0023'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'asset_id', name='uq_risk_asset')
    )
    op.create_table('continuity_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_ref', sa.String(length=32), nullable=False),
    sa.Column('bia_id', sa.Integer(), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('recovery_hours', sa.Float(), nullable=False),
    sa.Column('data_loss_hours', sa.Float(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=False),
    sa.Column('target_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('recovery_hours >= 0 AND data_loss_hours >= 0', name='ck_exercise_measurements'),
    sa.ForeignKeyConstraint(['bia_id'], ['business_impact_analyses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_ref')
    )
    op.create_table('operational_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('coverage_note', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('period_end >= period_start AND review_date >= period_end', name='ck_operational_evidence_dates'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('record_ref', sa.String(length=24), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('previous', sa.JSON(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_on', sa.Date(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('ASSET','ROPA','DPIA','BIA')", name='ck_register_kind'),
    sa.CheckConstraint("status != 'REVIEWED' OR (reviewed_by IS NOT NULL AND reviewed_on IS NOT NULL AND evidence_id IS NOT NULL)", name='ck_register_review'),
    sa.CheckConstraint("status IN ('DRAFT','REVIEWED')", name='ck_register_status'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'record_ref', 'revision', name='uq_register_revision')
    )
    op.create_table('operational_review_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status != 'RESOLVED' OR (evidence_id IS NOT NULL AND resolved_by IS NOT NULL AND length(trim(coalesce(resolution,'')))>0)", name='ck_operational_task_resolution'),
    sa.CheckConstraint("status IN ('OPEN','RESOLVED')", name='ck_operational_task_status'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id'], ['register_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'risk_id', name='uq_operational_review')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_review_tasks')
    op.drop_table('register_revisions')
    op.drop_table('operational_evidence')
    op.drop_table('continuity_exercises')
    op.drop_table('risk_assets')
    # ### end Alembic commands ###
