"""retain monitoring basis and risk assessment history

Revision ID: 0025
Revises: 0024
Create Date: 2026-09-28 00:47:19.843313
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0025'
down_revision: str | None = '0024'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('population', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('collection_owner', sa.String(length=160), nullable=False),
    sa.Column('evaluation_owner', sa.String(length=160), nullable=False),
    sa.Column('frequency', sa.String(length=80), nullable=False),
    sa.Column('next_collection', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kri_id')
    )
    op.create_table('risk_assessment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('source_query', sa.Text(), nullable=False),
    sa.Column('population', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('definition_snapshot', sa.JSON(), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=True),
    sa.Column('evaluated_by', sa.String(length=64), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('remediation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("band IN ('GREEN','AMBER','RED','NO_DATA')", name='ck_monitoring_band'),
    sa.CheckConstraint("evaluated_on IS NULL OR (evaluated_by IS NOT NULL AND length(trim(coalesce(evaluation,'')))>0)", name='ck_monitoring_evaluation'),
    sa.CheckConstraint('period_end >= period_start', name='ck_monitoring_period'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['measurement_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'period_end', name='uq_monitoring_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoring_observations')
    op.drop_table('risk_assessment_snapshots')
    op.drop_table('measurement_plans')
    # ### end Alembic commands ###
