"""bound AI diagnostics and retain pruning results

Revision ID: 0027
Revises: 0026
Create Date: 2026-09-28 00:57:42.613451
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0027'
down_revision: str | None = '0026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_count', sa.Integer(), nullable=False),
    sa.Column('policy', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retention_state')
    # ### end Alembic commands ###
