"""serialize reference allocation without losing authored identifiers

Revision ID: 0028
Revises: 0027
Create Date: 2026-09-28 01:11:20.373415
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0028'
down_revision: str | None = '0027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_counters',
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('last_value >= 0', name='ck_reference_counter_nonnegative'),
    sa.PrimaryKeyConstraint('prefix')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_counters')
    # ### end Alembic commands ###
